version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1  # Удалите или измените для продакшена
      - DJANGO_SETTINGS_MODULE=restaurant_sourse.settings
#    depends_on:
#      - db
#  db:
#    image: postgres:13
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: youruser
#      POSTGRES_PASSWORD: yourpassword
#      POSTGRES_DB: yourdb

volumes:
  postgres_data:
